export const bigSliderItems = [
  {
    id: 1,
    img: 'https://images.pexels.com/photos/1200450/pexels-photo-1200450.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '16+',
  },
  {
    id: 2,
    img: 'https://images.pexels.com/photos/65437/pexels-photo-65437.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '18+',
  },
  {
    id: 3,
    img: 'https://images.pexels.com/photos/458379/pexels-photo-458379.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '13+',
  },
  {
    id: 4,
    img: 'https://images.pexels.com/photos/2398354/pexels-photo-2398354.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '16+',
  },
  {
    id: 5,
    img: 'https://images.pexels.com/photos/157543/pexels-photo-157543.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '16+',
  },
  {
    id: 6,
    img: 'https://images.pexels.com/photos/3137890/pexels-photo-3137890.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '13+',
  },
  {
    id: 7,
    img: 'https://images.pexels.com/photos/950835/pexels-photo-950835.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '16+',
  },
  {
    id: 8,
    img: 'https://images.pexels.com/photos/2398356/pexels-photo-2398356.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '16+',
  },
  {
    id: 9,
    img: 'https://images.pexels.com/photos/3767825/pexels-photo-3767825.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '16+',
  },
  {
    id: 10,
    img: 'https://images.pexels.com/photos/1200450/pexels-photo-1200450.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '16+',
  },
  {
    id: 11,
    img: 'https://images.pexels.com/photos/1200450/pexels-photo-1200450.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '16+',
  },
  {
    id: 12,
    img: 'https://images.pexels.com/photos/1200450/pexels-photo-1200450.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '16+',
  },
  {
    id: 13,
    img: 'https://images.pexels.com/photos/1200450/pexels-photo-1200450.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '16+',
  },
  {
    id: 14,
    img: 'https://images.pexels.com/photos/1200450/pexels-photo-1200450.jpeg?auto=compress&cs=tinysrgb&w=400',
    subImg: '/info-title.png',
    isInPrime: true,
    rate: '16+',
  },
];
